# Generated by Django 3.1.7 on 2021-03-29 11:11

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(50)])),
                ('region', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('delivery_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator('^([01]?\\d|2[0-3]):([0-5]\\d)-([01]?\\d|2[0-3]):([0-5]\\d)$', 'Incorrect time range.')]), size=None)),
                ('courier_assigned', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RegionTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.IntegerField()),
                ('last_finished_time', models.DateTimeField(null=True)),
                ('times', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('courier_type', models.CharField(choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=4)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]), size=None)),
                ('working_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator('^([01]?\\d|2[0-3]):([0-5]\\d)-([01]?\\d|2[0-3]):([0-5]\\d)$', 'Incorrect time range.')]), blank=True, size=None)),
                ('assigned_orders', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('assigned_time', models.DateTimeField(blank=True, null=True)),
                ('earnings', models.IntegerField(default=0)),
                ('region_time', models.ManyToManyField(to='couriers.RegionTime')),
            ],
        ),
    ]
